
networks:
  nginx-forward-proxy:
    driver: bridge


services:
  nginx-forward-proxy:
    container_name: nginx-forward-proxy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx-forward-proxy
    ports:
      - 8080:80
 